### ISSUE TITLE
why is subtype url?

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscale_core#109]
![image](https://user-images.githubusercontent.com/6021844/44828524-968fd000-ac18-11e8-8c5e-251745b37e9a.png)

why is subtype url?
don't see where it comes from

was trying to do
js_code get -a threefoldtech -f

please check this function

**Comment by delandtj** [comment]
it's because "check" on "*", which is a string, is matching URL.  it's an extremely obscure bug where the order of the checking that's done is critically important (and shouldn't be... or should have been properly documented).  so because a string happened to be passed in that matched URL, and URL was in the list of types earlier than string, the type of "List" was set to URL.

which tends to suggest that there is an additional bug: URL should never be matching against "*" in the first place.
